### ISSUE TITLE
[FR] Best Toggle UI design

### ISSUE THREAD

**Issue by cprodhomme** [platanus/activeadmin_addons#461]
**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

I have recently change the style of your toggle with a design more modern in arctic_admin : 

![Capture d’écran 2023-04-13 à 16 18 39](https://user-images.githubusercontent.com/7428736/231788389-3db25c7d-0a28-4c06-917b-79b4f0bb2122.png)

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*

I ask if you want to reuse the style or not ? :) 

I can made the pull request if you want some help

**Additional context**
*Add any other context or screenshots about the feature request here.(

The style i use : 

Just thinks to remove the between the `// reset style`

```scss
$toggle-width: 40px !default;
$toggle-height: 20px !default;
$toggle-offset: 3px !default;

$toggle-outer-default: #ddd !default;
$toggle-outer-active: $primary-color !default;
$toggle-inner-default: #fff !default;
$toggle-inner-active: #fff !default;

$toggle-transition: 200ms ease-out !default;

.toggle-bool-switches-container {

  text-align: left;

  .toggle-bool-switch {
    // reset style
    background-image: none;
    box-shadow: none;
    //

    cursor: pointer;

    position: relative;
    display: inline-flex;
    align-items: center;
    width: var(--toggle-width);
    height: var(--toggle-height);
    background-color: var(--toggle-outer-default);
    border-radius: 100vw;
    cursor: pointer;
    transition: var(--toggle-transition);

    &::before {
      // reset style
      height: auto;
      width: auto;
      background-image: none;
      //


      content: "";
      position: absolute;
      top: var(--toggle-offset);
      left: var(--toggle-offset);
      bottom: var(--toggle-offset);
      
      aspect-ratio: 1 / 1;
      
      background-color: var(--toggle-inner-default);
      border-radius: 50%;
      box-shadow: 0 0 10px 5px rgba(0, 0, 0, 0.05);
      transition: var(--toggle-transition);
    }

    &.on {
      // reset style
      background-image: none;
      //
      background: $primary-color;

      &::before {
        // reset style
        left: var(--toggle-offset);
        //

        background-color: var(--toggle-inner-active);
        transform: translateX(
          calc(var(--toggle-width) - var(--toggle-height))
        );
      }
    }
  }
}

```
