### ISSUE TITLE
[BUG] Select UI styling lost when using `activeadmin` `3.2.0`

### ISSUE THREAD

**Issue by Aurea-Li** [platanus/activeadmin_addons#490]
**Describe the bug**
The current `activeadmin_addons` gem I'm using is the latest stable, `1.10.1`. After upgrading `activeadmin` from `2.12.0` to `3.2.0`, I noticed that all select boxes lost their styling.

**To Reproduce**
1. Install version `3.2.0` of `activeadmin`, and version `1.10.1` of `activeadmin_addons`. 
2. Spin up an instance of admin.

**Expected behavior**
![image](https://github.com/platanus/activeadmin_addons/assets/34611634/01092748-6792-4a93-bf94-8d7bdbe4c4dd)

**Screenshots**
![image](https://github.com/platanus/activeadmin_addons/assets/34611634/a643e94a-9fd7-4526-affb-ccc12f01a16a)

**Additional context**
Here are the imports from my `active_admin.scss` file.
```
@import 'active_admin_custom/mixins/variables';
@import 'active_admin/mixins';
@import 'active_admin_custom/mixins';
@import 'active_admin/base';
@import 'active_admin_custom/base';
@import 'activeadmin_addons/all';
@import 'activeadmin/quill_editor/quill.snow';
@import 'activeadmin/quill_editor_input';
@import 'tooltip/base';
@import 'c3';
@import 'jsoneditor';
```

Here are the imports from my `active_admin.js` file.
```
//= require active_admin/base
//= require activeadmin_addons/all
//= require activeadmin/quill_editor_input
//= require activeadmin/quill_editor/quill
//= require activestorage
//= require c3
//= require d3
//= require jsoneditor

//= require ./copy_to_clipboard_helpers
//= require ./jsoneditor_helpers
//= require ./organization
```

I don't have anything set in `ActiveadminAddons.setup do |config|`, and I'm not running `config.register_stylesheet` anywhere in `ActiveAdmin.setup do |config|`.

**Comment by haaayden** [comment]
I'm using activeadmin 3.2.0 without activeadmin_addons and I'm also experiencing this issue, makes me think it isn't activeadmin_addons related.

Using this [reference](https://github.com/activeadmin/activeadmin/blob/v3.2.0/app/assets/stylesheets/active_admin/_forms.scss#L117), I added the following to `active_admin.scss` and it made things look much more consistent for me:

```scss
form select {
  border: $border-width solid #c9d0d6;
  @include rounded;
  font-size: 0.95em;
  @include sans-family;
  outline: none;
  padding: 7px $text-input-horizontal-padding 6px;

  &:focus {
    border: $border-width solid #99a2aa;
    @include shadow(0,0,4px,#99a2aa);
  }
}
```

Hope that helps @Aurea-Li
