### ISSUE TITLE
Custom css class for bool_row and bool_column

### ISSUE THREAD

**Issue by anthony-robin** [platanus/activeadmin_addons#53]
It could be a good idea to add a css class to bool_row and bool_column representing the value of the boolean. This could permit to customize the color or the size of the icon.

For example: 
```html
<td class="col bool_icon bool_true">✔</td>
<td class="col bool_icon bool_false">✗</td>
```

```css
.bool_icon {
  font-size: 20px;
}
.bool_true {
  color: green;
}
.bool_false {
  color: red;
}
```
